name: Build LaTeX documents

on:
  push:
    paths:
      - '**.tex'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Compile all LaTeX documents
        uses: xu-cheng/latex-action@v3
        with:
          root_file: '*.tex'

      - name: Upload PDFs
        uses: actions/upload-artifact@v4
        with:
          name: PDFs
          path: '*.pdf'