name: Build LaTeX document

on:
  push:
    paths:
      - '**.tex'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: beans.tex

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: beans.pdf